apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geneweb
  namespace: geneweb
spec:
  rules:
  - host: geneweb.10.30.0.30.nip.io
    http:
      paths:
      - backend:
          service:
            name: geneweb
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - geneweb.10.30.0.30.nip.io