apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geneweb-pvc
  namespace: geneweb
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
